services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: MuzBot
    restart: unless-stopped

    env_file:
      - ./.env
    init: true
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_NAME=${DB_NAME}
      - TRACKS_PER_LIMIT=${TRACKS_PER_LIMIT}
      - QUERY_DOWNLOAD_LIMIT_SECS=${QUERY_DOWNLOAD_LIMIT_SECS}
      - CPU_COUNT=${CPU_COUNT}

    volumes:
       - type: bind
         source: ./data
         target: /muzbot/data
    networks:
      - bot
    # REMOVE IF YOU DON'T NEED LOKI 
    depends_on:
      loki:
        condition: service_healthy
        required: false
    healthcheck:
      test: ["CMD-SHELL", "python healthcheck.py > /proc/1/fd/1 2>&1 || exit 1"]
      interval: 5m    
      timeout: 8s      
      retries: 3       
      start_period: 1s 

  loki:
    image: grafana/loki:3.0.0
    container_name: loki_service
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - bot
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3100/ready | grep -q 'ready' || exit 1"]
      interval: 5s     
      timeout: 5s      
      retries: 5       
      start_period: 10s 

    profiles: [mon]

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana_service
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - bot
    depends_on:
      - loki
    profiles: [mon]
    
networks:
  bot:
    driver: bridge