services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: MuzBot
    restart: unless-stopped

    env_file:
      - ./.env
    init: true
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_NAME=${DB_NAME}
      - TRACKS_PER_LIMIT=${TRACKS_PER_LIMIT}
      - QUERY_DOWNLOAD_LIMIT_SECS=${QUERY_DOWNLOAD_LIMIT_SECS}
      - CPU_COUNT=${CPU_COUNT}

    volumes:
       - type: bind
         source: ./data
         target: /muzbot/data

    healthcheck:
      test: ["CMD-SHELL", "python healthcheck.py > /proc/1/fd/1 2>&1 || exit 1"]
      interval: 30m    # Как часто проверять
      timeout: 8s      # Сколько ждать ответа от скрипта
      retries: 3       # Количество неудачных попыток до статуса "unhealthy"
      start_period: 1s # Сколько секунд дать боту на запуск перед первой проверкой
